targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          include:
            - lib/src/data/dto/**.dart
        options:
          any_map: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          