name: appwrite_clean
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  appwrite: ^12.0.0-rc.4
  awesome_flutter_extensions: ^1.2.0
  cached_network_image: ^3.3.1
  camera: ^0.10.5+9
  dio: ^5.4.1
  equatable: ^2.0.5
  flex_seed_scheme: ^1.4.0
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.8
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  flutter_gutter: ^1.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_secure_storage: ^9.0.0
  form_builder_validators: ^9.1.0
  get_it: ^7.6.7
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  injectable: ^2.3.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  locale_names: ^1.1.1
  material_symbols_icons: ^4.2719.1
  meta: ^1.11.0
  package_info_plus: ^4.2.0
  retrofit: ^4.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  retrofit_generator: ^8.1.0
  test: ^1.24.9
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  # generate: true
  assets:
    - .env.dev
    - .env.stag
    - .env.prod
    - assets/

flutter_gen:
  output: lib/src/assets/generated
